// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package client

import (
	"sync"
)

// Ensure, that CipherStub does implement Cipher.
// If this is not the case, regenerate this file with moq.
var _ Cipher = &CipherStub{}

// CipherStub is a stub implementation of Cipher.
//
//	func TestSomethingThatUsesCipher(t *testing.T) {
//
//		// make and configure a stubbed Cipher
//		stubbedCipher := &CipherStub{
//			DecryptFunc: func(cipherTextFile string, plainTextFile string) error {
//				panic("stub out the Decrypt method")
//			},
//			EncryptFunc: func(plainTextFile string, cipherTextFile string) error {
//				panic("stub out the Encrypt method")
//			},
//		}
//
//		// use stubbedCipher in code that requires Cipher
//		// and then make assertions.
//
//	}
type CipherStub struct {
	// DecryptFunc stubs the Decrypt method.
	DecryptFunc func(cipherTextFile string, plainTextFile string) error

	// EncryptFunc stubs the Encrypt method.
	EncryptFunc func(plainTextFile string, cipherTextFile string) error

	// calls tracks calls to the methods.
	calls struct {
		// Decrypt holds details about calls to the Decrypt method.
		Decrypt []struct {
			// CipherTextFile is the cipherTextFile argument value.
			CipherTextFile string
			// PlainTextFile is the plainTextFile argument value.
			PlainTextFile string
		}
		// Encrypt holds details about calls to the Encrypt method.
		Encrypt []struct {
			// PlainTextFile is the plainTextFile argument value.
			PlainTextFile string
			// CipherTextFile is the cipherTextFile argument value.
			CipherTextFile string
		}
	}
	lockDecrypt sync.RWMutex
	lockEncrypt sync.RWMutex
}

// Decrypt calls DecryptFunc.
func (stub *CipherStub) Decrypt(cipherTextFile string, plainTextFile string) error {
	if stub.DecryptFunc == nil {
		panic("CipherStub.DecryptFunc: method is nil but Cipher.Decrypt was just called")
	}
	callInfo := struct {
		CipherTextFile string
		PlainTextFile  string
	}{
		CipherTextFile: cipherTextFile,
		PlainTextFile:  plainTextFile,
	}
	stub.lockDecrypt.Lock()
	stub.calls.Decrypt = append(stub.calls.Decrypt, callInfo)
	stub.lockDecrypt.Unlock()
	return stub.DecryptFunc(cipherTextFile, plainTextFile)
}

// DecryptCalls gets all the calls that were made to Decrypt.
// Check the length with:
//
//	len(stubbedCipher.DecryptCalls())
func (stub *CipherStub) DecryptCalls() []struct {
	CipherTextFile string
	PlainTextFile  string
} {
	var calls []struct {
		CipherTextFile string
		PlainTextFile  string
	}
	stub.lockDecrypt.RLock()
	calls = stub.calls.Decrypt
	stub.lockDecrypt.RUnlock()
	return calls
}

// Encrypt calls EncryptFunc.
func (stub *CipherStub) Encrypt(plainTextFile string, cipherTextFile string) error {
	if stub.EncryptFunc == nil {
		panic("CipherStub.EncryptFunc: method is nil but Cipher.Encrypt was just called")
	}
	callInfo := struct {
		PlainTextFile  string
		CipherTextFile string
	}{
		PlainTextFile:  plainTextFile,
		CipherTextFile: cipherTextFile,
	}
	stub.lockEncrypt.Lock()
	stub.calls.Encrypt = append(stub.calls.Encrypt, callInfo)
	stub.lockEncrypt.Unlock()
	return stub.EncryptFunc(plainTextFile, cipherTextFile)
}

// EncryptCalls gets all the calls that were made to Encrypt.
// Check the length with:
//
//	len(stubbedCipher.EncryptCalls())
func (stub *CipherStub) EncryptCalls() []struct {
	PlainTextFile  string
	CipherTextFile string
} {
	var calls []struct {
		PlainTextFile  string
		CipherTextFile string
	}
	stub.lockEncrypt.RLock()
	calls = stub.calls.Encrypt
	stub.lockEncrypt.RUnlock()
	return calls
}
