// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package client

import (
	"context"
	"sync"
)

// Ensure, that StoreStub does implement Store.
// If this is not the case, regenerate this file with moq.
var _ Store = &StoreStub{}

// StoreStub is a stub implementation of Store.
//
//	func TestSomethingThatUsesStore(t *testing.T) {
//
//		// make and configure a stubbed Store
//		stubbedStore := &StoreStub{
//			DownloadFileFunc: func(ctx context.Context, remotePath string, localPath string) (string, error) {
//				panic("stub out the DownloadFile method")
//			},
//			UploadFileFunc: func(ctx context.Context, remotePath string, localPath string, checksum string) error {
//				panic("stub out the UploadFile method")
//			},
//		}
//
//		// use stubbedStore in code that requires Store
//		// and then make assertions.
//
//	}
type StoreStub struct {
	// DownloadFileFunc stubs the DownloadFile method.
	DownloadFileFunc func(ctx context.Context, remotePath string, localPath string) (string, error)

	// UploadFileFunc stubs the UploadFile method.
	UploadFileFunc func(ctx context.Context, remotePath string, localPath string, checksum string) error

	// calls tracks calls to the methods.
	calls struct {
		// DownloadFile holds details about calls to the DownloadFile method.
		DownloadFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RemotePath is the remotePath argument value.
			RemotePath string
			// LocalPath is the localPath argument value.
			LocalPath string
		}
		// UploadFile holds details about calls to the UploadFile method.
		UploadFile []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// RemotePath is the remotePath argument value.
			RemotePath string
			// LocalPath is the localPath argument value.
			LocalPath string
			// Checksum is the checksum argument value.
			Checksum string
		}
	}
	lockDownloadFile sync.RWMutex
	lockUploadFile   sync.RWMutex
}

// DownloadFile calls DownloadFileFunc.
func (stub *StoreStub) DownloadFile(ctx context.Context, remotePath string, localPath string) (string, error) {
	if stub.DownloadFileFunc == nil {
		panic("StoreStub.DownloadFileFunc: method is nil but Store.DownloadFile was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		RemotePath string
		LocalPath  string
	}{
		Ctx:        ctx,
		RemotePath: remotePath,
		LocalPath:  localPath,
	}
	stub.lockDownloadFile.Lock()
	stub.calls.DownloadFile = append(stub.calls.DownloadFile, callInfo)
	stub.lockDownloadFile.Unlock()
	return stub.DownloadFileFunc(ctx, remotePath, localPath)
}

// DownloadFileCalls gets all the calls that were made to DownloadFile.
// Check the length with:
//
//	len(stubbedStore.DownloadFileCalls())
func (stub *StoreStub) DownloadFileCalls() []struct {
	Ctx        context.Context
	RemotePath string
	LocalPath  string
} {
	var calls []struct {
		Ctx        context.Context
		RemotePath string
		LocalPath  string
	}
	stub.lockDownloadFile.RLock()
	calls = stub.calls.DownloadFile
	stub.lockDownloadFile.RUnlock()
	return calls
}

// UploadFile calls UploadFileFunc.
func (stub *StoreStub) UploadFile(ctx context.Context, remotePath string, localPath string, checksum string) error {
	if stub.UploadFileFunc == nil {
		panic("StoreStub.UploadFileFunc: method is nil but Store.UploadFile was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		RemotePath string
		LocalPath  string
		Checksum   string
	}{
		Ctx:        ctx,
		RemotePath: remotePath,
		LocalPath:  localPath,
		Checksum:   checksum,
	}
	stub.lockUploadFile.Lock()
	stub.calls.UploadFile = append(stub.calls.UploadFile, callInfo)
	stub.lockUploadFile.Unlock()
	return stub.UploadFileFunc(ctx, remotePath, localPath, checksum)
}

// UploadFileCalls gets all the calls that were made to UploadFile.
// Check the length with:
//
//	len(stubbedStore.UploadFileCalls())
func (stub *StoreStub) UploadFileCalls() []struct {
	Ctx        context.Context
	RemotePath string
	LocalPath  string
	Checksum   string
} {
	var calls []struct {
		Ctx        context.Context
		RemotePath string
		LocalPath  string
		Checksum   string
	}
	stub.lockUploadFile.RLock()
	calls = stub.calls.UploadFile
	stub.lockUploadFile.RUnlock()
	return calls
}
