package mocks

import mock "github.com/stretchr/testify/mock"

// Store is an autogenerated mock type for the Store type
type Store struct {
	mock.Mock
}

// DownloadFile provides a mock function with given fields: remotePath, localPath
func (_m *Store) DownloadFile(remotePath string, localPath string) (string, error) {
	ret := _m.Called(remotePath, localPath)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(remotePath, localPath)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(remotePath, localPath)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UploadFile provides a mock function with given fields: remotePath, localPath, checksum
func (_m *Store) UploadFile(remotePath string, localPath string, checksum string) error {
	ret := _m.Called(remotePath, localPath, checksum)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(remotePath, localPath, checksum)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
