#!/usr/bin/env bash
set -eo pipefail

grep -r -l 'Code generated by moq' --include='*.go' | grep -v 'vendor/' | while read -r src; do
  echo "Converting ${src} ..."
  sed 's/mocked/stubbed/g;s/mock/stub/g' "${src}" > "${src}.temp"
  mv "${src}.temp" "${src}"
done
